/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adorkw_encrypterandroid_Encrypter_Companion */

#ifndef _Included_com_adorkw_encrypterandroid_Encrypter_Companion
#define _Included_com_adorkw_encrypterandroid_Encrypter_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adorkw_encrypterandroid_Encrypter_Companion
 * Method:    generateRandomKey
 * Signature: (I)V
 */
JNIEXPORT jstring JNICALL Java_com_adorkw_encrypterandroid_Encrypter_00024Companion_generateRandomKey
  (JNIEnv* env, jobject, jint s);

#ifdef __cplusplus
}
#endif
#endif
